[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @collabify/api exec prisma generate && pnpm --filter @collabify/api build"]

[start]
cmd = "cd apps/api && node dist/main"
